apiVersion: v1
kind: Pod
metadata:
  name: docker-pod
spec:
  securityContext:
      fsGroup: 412
  containers:
  - name: sec-ctx-demo
    image: docker:dind
    securityContext:
      runAsUser: 0
      privileged: true
