apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: 1
globalDefault: false
description: "Some desc."
preemptionPolicy: Never # ahead of other pods, but not preempt current running