apiVersion: v1
kind: Pod
metadata:
  name: nginx-high-priority
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 700m
  priorityClassName: high-priority