apiVersion: apps/v1
kind: Deployment
metadata:
  name: roling
  labels:
    app: qos
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
    type: RollingUpdate
  selector:
    matchLabels:
      app: qos
  template:
    metadata:
      name: qos-pod
      labels:
        app: qos
    spec:
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', 'sleep 60']
      containers:
      - name: myapp-container
        image: ewoutp/docker-nginx-curl
        ports:
          - containerPort: 80
        env:
          - name: TESTENV
            value: "30"