apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling
  labels:
    app: rolling
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
    type: RollingUpdate
  selector:
    matchLabels:
      app: rolling
  template:
    metadata:
      name: rolling-pod
      labels:
        app: rolling
    spec:
      containers:
      - name: myapp-container
        image: ewoutp/docker-nginx-curl
        ports:
          - containerPort: 80
        env:
          - name: TESTENV
            value: "40"
