apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-2
  labels:
    app: myapp
    type: server
  annotations:
    comes-from/file: file.txt
spec:
  containers:
  - name: myapp-container
    image: ewoutp/docker-nginx-curl
